export const colors = {
  bg: '#FFFFFF',
  surface: '#FFFFFF',
  card: '#FFFFFF',
  text: '#0D0D0D',
  textSecondary: '#4E4E4E',
  textMuted: '#9A9A9A',
  border: '#DCDCDC',
  tabBar: '#0D0D0D',
  accent: '#B7E43A',
  white: '#FFFFFF',
  yellow: '#B7E43A',
  yellowCard: '#F3F8DE',
  blue: '#B7E43A',
  blueCard: '#EEF7CF',
  lavender: '#0D0D0D',
  lavenderCard: '#F4F4F4',
  green: '#B7E43A',
  red: '#FF3B30',
};
